export const SIGNUP_ACTION_SUCCESS = 'SIGNUP_ACTION_SUCCESS'
export const SIGNUP_ACTION_FAILED = 'SIGNUP_ACTION_FAILED'

export const SIGNOUT_ACTION_SUCCESS = 'SIGNOUT_ACTION_SUCCESS'
export const SIGNOUT_ACTION_FAILED = 'SIGNOUT_ACTION_FAILED'
